name: Build and Release binaries (Linux x86 & ARM)

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64, armhf, armv7]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential git curl libssl-dev zlib1g-dev gcc-aarch64-linux-gnu gcc-arm-linux-gnueabihf

      - name: Build for amd64
        if: matrix.arch == 'amd64'
        run: make m=64

      - name: Build for arm64
        if: matrix.arch == 'arm64'
        run: make CC=aarch64-linux-gnu-gcc ARCH="-march=armv8-a"

      - name: Build for armhf
        if: matrix.arch == 'armhf'
        run: make CC=arm-linux-gnueabihf-gcc ARCH="-march=armv7-a"

      - name: Build for armv7
        if: matrix.arch == 'armv7'
        run: make CC=arm-linux-gnueabihf-gcc ARCH="-march=armv7-a"

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: mtproto-proxy-Linux-${{ matrix.arch }}
          path: objs/bin/mtproto-proxy
